server:
  port: 8001
spring:
 #邮箱配置
  mail:
    port: 587
    host: smtp.qq.com
    username: 1539429627@qq.com
   #QQ邮箱的授权码
    password: fbmtjksiwwxbgbej
    default-encoding: UTF-8
    properties:
      mail:
          properties:
            mail:
              smtp:
                localhost: localhost
                auth: true
                starttls:
                  enable: true
                  required: true
  datasource:
    url: jdbc:mysql://47.105.179.209:3306/zls?useUnicode=true&characterEncoding=utf8
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
spring.servlet.multipart.maxFileSize: 10000MB
spring.servlet.multipart.maxRequestSize: 10000MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qf.pojo

